name: hive
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.9.0
  google_mlkit_digital_ink_recognition: ^0.12.0
  flutter_bloc: ^8.1.3

  freezed_annotation: ^2.4.1
  injectable: ^2.4.2
  get_it: ^7.7.0
  go_router: ^14.1.4
  freezed: ^2.5.2
  firebase_core: ^2.27.1
  firebase_crashlytics: ^3.4.19
  firebase_analytics: ^10.8.10
  firebase_auth: ^4.17.9
  firebase_storage: ^11.6.11
  cloud_firestore: ^4.17.5
  image_picker: ^1.0.7

  formz: ^0.7.0
  flutter_widget_from_html_core: ^0.14.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  injectable_generator: ^2.6.1
  build_runner: ^2.4.10
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
